### ISSUE TITLE
No module named pyredner

### ISSUE THREAD

**Issue by MRamazan** [fraunhoferhhi/spvloc#1]
im getting No module named 'pyredner' error in the pvloc/spvloc/utils/render.py  file
im sure i created and activated conda env
'pip install pyredner' doesnt work
download instructions in this repo doesnt work either : https://github.com/BachiLi/redner

**Comment by gard-n** [comment]
Have you called the [scripts to install the additional dependencies](https://github.com/fraunhoferhhi/spvloc?tab=readme-ov-file#step-2-install-additional-dependencies)?

After calling `./data/setup/install_redner.sh` is should be possible to import redner. 

Best regards,
Niklas

**Comment by MRamazan** [comment]
yes it was my fault. I had already run those scripts, but
scripts were giving errors and I didn't see them . After fixing the errors and running it properly, the code works fine. 
thank you for your great work
